apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoidWdhcGFueXVrIiwicGFzc3dvcmQiOiJnaHBfNXBzMDVKTkx0MnM2dFlMb3RyVEY0YW9WYXhydFU0MjNHakFqIiwiYXV0aCI6ImRXZGhjR0Z1ZVhWck9tZG9jRjgxY0hNd05VcE9USFF5Y3paMFdVeHZkSEpVUmpSaGIxWmhlSEowVlRReU0wZHFRV289In19fQ==
type: kubernetes.io/dockerconfigjson
